#!/usr/bin/env bash
# This script prints information about domains and subdomains.

# Function to print information about a specific domain and subdomain
print_domain_subdomain () {
    # Use dig to query DNS records for the specified domain
    # Extract the "ANSWER SECTION" using grep
    # Replace the domain name with the subdomain name using sed
    # Parse and format the output using awk
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

# Check if two arguments are provided
if [ "$#" -eq 2 ]; then
    # Call print_domain_subdomain with the specific subdomain and domain name
    print_domain_subdomain "$2.$1" "$2"
else
    # If no subdomain is provided, call print_domain_subdomain for default subdomains
    print_domain_subdomain "www.$1" "www"
    print_domain_subdomain "lb-01.$1" "lb-01"
    print_domain_subdomain "web-01.$1" "web-01"
    print_domain_subdomain "web-02.$1" "web-02"
fi
