#!/usr/bin/env bash
# Transfer a file to your server

# Check if number of arguments is less than 3, if yes, display usage
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Transfer the file using scp to the user's home directory on the server
if scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip":~/; then
    echo "File transferred successfully."
else
    echo "Failed to transfer file."
fi

