#!/usr/bin/env bash
# Install Nginx if not already installed

if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

# Install Nginx if not already installed
if ! command -v nginx &> /dev/null; then
    apt update
    apt install -y nginx
fi

# Create a redirection configuration file
cat << EOF > /etc/nginx/sites-available/redirect_me
server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://gabrielhilarion.tech/new-page;
    }
}
EOF

# Create a symbolic link to enable the configuration
ln -sf /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test Nginx configuration
nginx -t

# Reload Nginx to apply changes
service nginx reload
