#!/usr/bin/env bash
# Check if the script is run as root

if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

# Install Nginx if not already installed
if ! command -v nginx &> /dev/null; then
    apt update
    apt install -y nginx
fi

# Create a custom 404 error page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

# Configure Nginx to use the custom 404 page
cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /usr/share/nginx/html;
    index index.html index.htm;

    server_name 515230-web-01;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOF

# Test Nginx configuration
nginx -t

# Reload Nginx to apply changes
service nginx reload
