#!/usr/bin/env bash
# returns a custom header on request

sudo apt-get -y update
sudo apt-get -y install nginx

sudo sed -i "6i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /usr/share/nginx/index/index.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/index/404.html

sudo service nginx start
