#!/usr/bin/env bash
# Path to the file

file="/etc/passwd"

# Check if the file exists
if [ -e "$file" ]; then
    # Read the file line by line
    while IFS=: read -r username _ userid groupid _ homedir shell; do
        # Extract additional information about the user
        info=$(grep "^$username:" /etc/passwd | cut -d ':' -f 5)
        # Extract password from shadow file
        password=$(grep "^$username:" /etc/shadow | cut -d ':' -f 2)
        
        # Print the desired information
        echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell."
        echo "User ID's place is protected by the passcode $password, more info about the user here: $info"
        echo
    done < "$file"
else
    echo "File not found: $file"
fi
