#!/usr/bin/env bash
# Using a while loop to loop from 1 to 10

counter=1
while [ $counter -le 10 ]; do
    if [ $counter -eq 4 ]; then
        echo "bad luck"
    elif [ $counter -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    # Increment counter
    ((counter++))
done
