#!/bin/bash

# Enable UFW
sudo ufw enable

# Deny all incoming traffic by default
sudo ufw default deny incoming

# Allow SSH (port 22)
sudo ufw allow 22/tcp

# Allow HTTP (port 80)
sudo ufw allow 80/tcp

# Allow HTTPS (port 443)
sudo ufw allow 443/tcp

# Reload UFW to apply the changes
sudo ufw reload

# Display the UFW status to confirm the changes
sudo ufw status verbose

echo -e "Process Completed.\n"