#!/usr/bin/env bash
# Define variables for server hostname or IP address, username, and private key file
private_key=~/.ssh/school
user=ubuntu
server=100.26.247.170

# SSH connection command
ssh -i "$private_key" "$user"@"$server"
